<?xml version="1.0" encoding="UTF-8"?><definitions name="SiantelService" targetNamespace="http://www.telcel.com.mx/siantel/wmb" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://www.telcel.com.mx/siantel/wmb" xmlns:types="http://www.telcel.com.mx/siantel" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <documentation>
    <appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="SiantelBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </appinfo>
  </documentation>
	<types>
		<xsd:schema>
		<xsd:import schemaLocation="siantel.xsd" namespace="http://www.telcel.com.mx/siantel" />
</xsd:schema>
	</types>
	
	<message name="getPerfilTelefonoRequest">
		<part element="types:SolicitudPerfilTelefono" name="parameters"/>
	</message>
	<message name="getPerfilTelefonoResponse">
		<part element="types:PerfilTelefono" name="parameters"/>
	</message>
	<message name="getPerfilTelefonoFault">
		<part element="types:Error" name="parameters"/>
	</message>
	
	<portType name="SiantelPort">
		<operation name="getPerfilTelefono">
			<input message="this:getPerfilTelefonoRequest"/>
			<output message="this:getPerfilTelefonoResponse"/>
			<fault message="this:getPerfilTelefonoFault" name="fault"/>
		</operation>
	</portType>
	
	<binding name="SiantelBinding" type="this:SiantelPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="getPerfilTelefono">
			<soap:operation soapAction="http://www.telcel.com.mx/siantel/wmb/getPerfilTelefono"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="getPerfilTelefonoFault">
				<soap:fault name="getPerfilTelefonoFault" use="literal"/>
			</fault>
		</operation>
	</binding>
	
	<service name="SiantelService">
		<port binding="this:SiantelBinding" name="Siantel">
			<soap:address location="http://localhost:7800/siantel/wmb/SiantelService"/>
		</port>
	</service>
</definitions>