<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://tramitesbpm.ws.dsie.gsa.sds.di.telcel.com/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="TramitesBPMService" targetNamespace="http://tramitesbpm.ws.dsie.gsa.sds.di.telcel.com/">
  <documentation>
    <appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="TramitesBPMPortBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </appinfo>
  </documentation>
  <types>
    <xsd:schema>
      <xsd:import namespace="http://tramitesbpm.ws.dsie.gsa.sds.di.telcel.com/" schemaLocation="TramitesBPMService.xsd"/>
    </xsd:schema>
  </types>
  <message name="envioSMS">
    <part element="tns:envioSMS" name="parameters">
		</part>
  </message>
  <message name="envioSMSResponse">
    <part element="tns:envioSMSResponse" name="parameters">
		</part>
  </message>
  <portType name="TramitesBPM">
    <operation name="envioSMS">
      <input message="tns:envioSMS" wsam:Action="http://tramitesbpm.ws.dsie.gsa.sds.di.telcel.com/TramitesBPM/envioSMSRequest">
		</input>
      <output message="tns:envioSMSResponse" wsam:Action="http://tramitesbpm.ws.dsie.gsa.sds.di.telcel.com/TramitesBPM/envioSMSResponse">
		</output>
    </operation>
  </portType>
  <binding name="TramitesBPMPortBinding" type="tns:TramitesBPM">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="envioSMS">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="TramitesBPMService">
    <port binding="tns:TramitesBPMPortBinding" name="TramitesBPMPort">
      <soap:address location="http://intranet.telcel.com:8000/TramitesBPM/TramitesBPMService"/>
    </port>
  </service>
</definitions>
