<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:comun="http://www.telcel.com.mx/di/sds/servicioaclientes/gestiontramites/wmb/comun/schema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://www.telcel.com.mx/di/sds/servicioaclientes/gestiontramites/wmb/notificaciones" xmlns:types="http://www.telcel.com.mx/di/sds/servicioaclientes/gestiontramites/wmb/notificaciones/schema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="GestionTramitesNotificaciones" targetNamespace="http://www.telcel.com.mx/di/sds/servicioaclientes/gestiontramites/wmb/notificaciones">
	<documentation>
		<appinfo source="WMQI_APPINFO">
			<MRWSDLAppInfo imported="true">
				<binding hasEncoding="false" imported="true" name="GestionTramitesNotificacionesBinding" originalBindingStyle="document"/>
			</MRWSDLAppInfo>
		</appinfo>
	</documentation>
	<types>
		<xsd:schema>
			<xsd:import namespace="http://www.telcel.com.mx/di/sds/servicioaclientes/gestiontramites/wmb/notificaciones/schema" schemaLocation="GestionTramitesNotificaciones.xsd"/>
			<xsd:import namespace="http://www.telcel.com.mx/di/sds/servicioaclientes/gestiontramites/wmb/comun/schema" schemaLocation="../comun/GestionTramitesComun.xsd"/>
		</xsd:schema>
	</types>
	<message name="enviarSMSMsg">
		<part element="types:enviarSMSRequest" name="parameters"/>
	</message>
	<message name="enviarSMSMsgResponse">
		<part element="types:enviarSMSResponse" name="parameters"/>
	</message>
	<message name="gestionTramitesWMBExceptionMsg">
		<part element="comun:gestionTramitesWMBException" name="fault"/>
	</message>
	<portType name="GestionTramitesNotificacionesPort">
		<operation name="enviarSMS">
			<input message="this:enviarSMSMsg"/>
			<output message="this:enviarSMSMsgResponse"/>
			<fault message="this:gestionTramitesWMBExceptionMsg" name="GestionTramitesWMBException"/>
		</operation>
	</portType>
	<binding name="GestionTramitesNotificacionesBinding" type="this:GestionTramitesNotificacionesPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

		<operation name="enviarSMS">
			<soap:operation soapAction="http://www.telcel.com.mx/di/sds/servicioaclientes/gestiontramites/wmb/notificaciones/enviarSMS"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="GestionTramitesWMBException">
				<soap:fault name="GestionTramitesWMBException" use="literal"/>
			</fault>
		</operation>
	</binding>
	<service name="GestionTramitesNotificacionesService">
		<port binding="this:GestionTramitesNotificacionesBinding" name="GestionTramitesNotificacionesHTTPSOAPPort">
			<soap:address location="http://localhost:7800/di/sds/servicioaclientes/gestiontramites/wmb/NotificacionesService"/>
		</port>
	</service>
</definitions>
