<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="INotificacionCorreoSoapWSService" targetNamespace="http://impl.notificacion.webservice.ws.nci.profuturo.mx/" xmlns:ns1="http://notificacion.webservice.ws.nci.profuturo.mx/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://impl.notificacion.webservice.ws.nci.profuturo.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="INotificacionCorreoSoapWSServiceSoapBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
	<wsdl:import location="INotificacionCorreoSoapWS.wsdl" namespace="http://notificacion.webservice.ws.nci.profuturo.mx/">
	</wsdl:import>
	<wsdl:binding name="INotificacionCorreoSoapWSServiceSoapBinding" type="ns1:INotificacionCorreoSoapWS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getNotificacion">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input name="getNotificacion">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getNotificacionResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="INotificacionCorreoSoapWSService">
		<wsdl:port binding="tns:INotificacionCorreoSoapWSServiceSoapBinding" name="INotificacionCorreoSoapWSPort">
			<soap:address location="http://7.211.100.47:9080/mit-ws/services/INotificacionCorreoSoapWSService"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>