<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="IBitacoraProcesoSoapWSService" targetNamespace="http://impl.bitacora.webservice.ws.nci.profuturo.mx/" xmlns:ns1="http://bitacora.webservice.ws.nci.profuturo.mx/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://impl.bitacora.webservice.ws.nci.profuturo.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="IBitacoraProcesoSoapWSServiceSoapBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:import location="IBitacoraProcesoSoapWSService_i.wsdl" namespace="http://bitacora.webservice.ws.nci.profuturo.mx/">
    </wsdl:import>
  <wsdl:binding name="IBitacoraProcesoSoapWSServiceSoapBinding" type="ns1:IBitacoraProcesoSoapWS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultarBitacora">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="consultarBitacora">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="consultarBitacoraResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="guardarBitacora">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="guardarBitacora">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="guardarBitacoraResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="IBitacoraProcesoSoapWSService">
    <wsdl:port binding="tns:IBitacoraProcesoSoapWSServiceSoapBinding" name="IBitacoraProcesoSoapWSPort">
      <soap:address location="http://130.40.38.18:8080/mit-ws/services/IBitacoraProcesoSoapWSService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>