<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="ITipoSubcuentaSoapWSService" targetNamespace="http://impl.tipoSubcuenta.webservice.ws.nci.profuturo.mx/" xmlns:ns1="http://tipoSubcuenta.webservice.ws.nci.profuturo.mx/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://impl.tipoSubcuenta.webservice.ws.nci.profuturo.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="ITipoSubcuentaSoapWSServiceSoapBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:import location="ITipoSubcuentaSoapWSService_i.wsdl" namespace="http://tipoSubcuenta.webservice.ws.nci.profuturo.mx/">
    </wsdl:import>
  <wsdl:binding name="ITipoSubcuentaSoapWSServiceSoapBinding" type="ns1:ITipoSubcuentaSoapWS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consulta">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="consulta">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="consultaResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ITipoSubcuentaSoapWSService">
    <wsdl:port binding="tns:ITipoSubcuentaSoapWSServiceSoapBinding" name="ITipoSubcuentaSoapWSPort">
      <soap:address location="http://wasnci.profuturo.mx:8000/mit-ws/services/ITipoSubcuentaSoapWSService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>