<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="IValorAccionSoapWSService" targetNamespace="http://impl.valorAccion.webservice.ws.nci.profuturo.mx/" xmlns:ns1="http://valorAccion.webservice.ws.nci.profuturo.mx/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://impl.valorAccion.webservice.ws.nci.profuturo.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="IValorAccionSoapWSServiceSoapBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:import location="IValorAccionSoapWSService_i.wsdl" namespace="http://valorAccion.webservice.ws.nci.profuturo.mx/">
    </wsdl:import>
  <wsdl:binding name="IValorAccionSoapWSServiceSoapBinding" type="ns1:IValorAccionSoapWS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultarDiaHabilMesSig">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="consultarDiaHabilMesSig">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="consultarDiaHabilMesSigResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="consultar">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="consultar">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="consultarResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="IValorAccionSoapWSService">
    <wsdl:port binding="tns:IValorAccionSoapWSServiceSoapBinding" name="IValorAccionSoapWSPort">
      <soap:address location="http://wasnci.profuturo.mx:8000/mit-ws/services/IValorAccionSoapWSService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>