<?xml version="1.0" encoding="UTF-8"?><definitions name="Igtoc48D" targetNamespace="http://www.telcel.com.mx/m2k/wmb/igtoc48/d" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:comun="http://www.telcel.com.mx/m2k" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://www.telcel.com.mx/m2k/wmb/igtoc48/d" xmlns:types="http://www.telcel.com.mx/m2k/igtoc48/d" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <documentation>
    <appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="Igtoc48DBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </appinfo>
  </documentation>
	<types>
		<xsd:schema>
<xsd:import namespace="http://www.telcel.com.mx/m2k/igtoc48/d" schemaLocation="m2k_igtoc48_d.xsd"/>
<xsd:import namespace="http://www.telcel.com.mx/m2k" schemaLocation="m2k.xsd"/>
</xsd:schema>
	</types>
	
	<message name="ejecutarServicioMsg">
		<part element="types:Request" name="parameters"/>
	</message>
	<message name="ejecutarServicioMsgResponse">
		<part element="types:RespuestaOK" name="parameters"/>
	</message>
	<message name="respuestaErrorMsg">
		<part element="comun:RespuestaError" name="fault"/>
	</message>
	
	<portType name="Igtoc48DPort">
		<operation name="ejecutarServicio">
			<input message="this:ejecutarServicioMsg"/>
			<output message="this:ejecutarServicioMsgResponse"/>
			<fault message="this:respuestaErrorMsg" name="RespuestaError"/>
		</operation>
	</portType>
	
	<binding name="Igtoc48DBinding" type="this:Igtoc48DPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="ejecutarServicio">
			<soap:operation soapAction="http://www.telcel.com.mx/m2k/wmb/igtoc48/d/ejecutarServicio"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="RespuestaError">
				<soap:fault name="RespuestaError" use="literal"/>
			</fault>
		</operation>
	</binding>
	
	<service name="Igtoc48DService">
		<port binding="this:Igtoc48DBinding" name="Igtoc48D">
			<soap:address location="http://localhost:7800/m2k/wmb/Igtoc48DService"/>
		</port>
	</service>
</definitions>