<?xml version="1.0" encoding="UTF-8"?><definitions name="Igtoc40C" targetNamespace="http://www.telcel.com.mx/m2k/wmb/igtoc40/c" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:comun="http://www.telcel.com.mx/m2k" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://www.telcel.com.mx/m2k/wmb/igtoc40/c" xmlns:types="http://www.telcel.com.mx/m2k/igtoc40/c" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<documentation>
		<appinfo source="WMQI_APPINFO">
			<MRWSDLAppInfo imported="true">
				<binding hasEncoding="false" imported="true" name="Igtoc40CBinding" originalBindingStyle="document"/>
			</MRWSDLAppInfo>
		</appinfo>
	</documentation>
	
	<types>
		<xsd:schema>
			<xsd:import namespace="http://www.telcel.com.mx/m2k/igtoc40/c" schemaLocation="m2k_igtoc40_c.xsd"/>
			<xsd:import namespace="http://www.telcel.com.mx/m2k" schemaLocation="m2k.xsd"/>
		</xsd:schema>
	</types>
	
	<message name="ejecutarServicioMsg">
		<part element="types:Request" name="parameters"/>
	</message>
	<message name="ejecutarServicioMsgResponse">
		<part element="types:RespuestaOK" name="parameters"/>
	</message>
	<message name="respuestaErrorFault">
		<part element="comun:RespuestaError" name="parameters"/>
	</message>
	
	<portType name="Igtoc40CPort">
		<operation name="ejecutarServicio">
			<input message="this:ejecutarServicioMsg"/>
			<output message="this:ejecutarServicioMsgResponse"/>
			<fault message="this:respuestaErrorFault" name="fault"/>
		</operation>
	</portType>
	
	<binding name="Igtoc40CBinding" type="this:Igtoc40CPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="ejecutarServicio">
			<soap:operation soapAction="http://www.telcel.com.mx/m2k/wmb/igtoc40/c/ejecutarServicio"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="fault">
				<soap:fault name="fault" use="literal"/>
			</fault>
		</operation>
	</binding>
	
	<service name="Igtoc40CService">
		<port binding="this:Igtoc40CBinding" name="Igtoc40C">
			<soap:address location="http://localhost:7800/m2k/wmb/Igtoc40CService"/>
		</port>
	</service>
</definitions>