<?xml version="1.0" encoding="UTF-8"?><definitions name="SumiqC" targetNamespace="http://www.telcel.com.mx/m2k/wmb/sumiq/c" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:comun="http://www.telcel.com.mx/m2k" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://www.telcel.com.mx/m2k/wmb/sumiq/c" xmlns:types="http://www.telcel.com.mx/m2k/sumiq/c" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <documentation>
    <appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="SumiqCBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </appinfo>
  </documentation>
	<types>
		<xsd:schema>
<xsd:import namespace="http://www.telcel.com.mx/m2k/sumiq/c" schemaLocation="m2k_sumiq_c.xsd"/>
<xsd:import namespace="http://www.telcel.com.mx/m2k" schemaLocation="m2k.xsd"/>
</xsd:schema>
	</types>
	
	<message name="ejecutarServicioMsg">
		<part element="types:Request" name="parameters"/>
	</message>
	<message name="ejecutarServicioMsgResponse">
		<part element="types:RespuestaOK" name="parameters"/>
	</message>
	<message name="respuestaErrorFault">
		<part element="comun:RespuestaError" name="parameters"/>
	</message>
	
	<portType name="SumiqCPort">
		<operation name="ejecutarServicio">
			<input message="this:ejecutarServicioMsg"/>
			<output message="this:ejecutarServicioMsgResponse"/>
			<fault message="this:respuestaErrorFault" name="fault"/>
		</operation>
	</portType>
	
	<binding name="SumiqCBinding" type="this:SumiqCPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="ejecutarServicio">
			<soap:operation soapAction="http://www.telcel.com.mx/m2k/wmb/sumiq/c/ejecutarServicio"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="RespuestaError">
				<soap:fault name="RespuestaError" use="literal"/>
			</fault>
		</operation>
	</binding>
	
	<service name="SumiqCService">
		<port binding="this:SumiqCBinding" name="SumiqC">
			<soap:address location="http://localhost:7800/m2k/wmb/SumiqCService"/>
		</port>
	</service>
</definitions>