<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.acmeOrders.com/OrderService" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="OrderService" targetNamespace="http://www.acmeOrders.com/OrderService">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedMXSD location="OrderService_InlineSchema1.mxsd"/>
        <binding hasEncoding="false" imported="true" name="OrderServiceSOAP" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
	<wsdl:types>
    <xsd:schema xmlns:mrm="http://www.acmeOrders.com/OrderService" targetNamespace="http://www.acmeOrders.com/OrderService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.acmeOrders.com/OrderService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:include schemaLocation="OrderService_InlineSchema1.mxsd"/>
    </xsd:schema>
  </wsdl:types>
	<wsdl:message name="submitPOResponse">
		<wsdl:part element="tns:submitPOResponse" name="submitPOResponse"/>
	</wsdl:message>
	<wsdl:message name="submitPORequest">
		<wsdl:part element="tns:submitPORequest" name="submitPORequest"/>
	</wsdl:message>
	<wsdl:portType name="OrderService">
		<wsdl:operation name="submitPO">
			<wsdl:input message="tns:submitPORequest"/>
			<wsdl:output message="tns:submitPOResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="OrderServiceSOAP" type="tns:OrderService">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="submitPO">
			<soap:operation soapAction="http://www.acmeOrders.com/OrderService"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="OrderService">
		<wsdl:port binding="tns:OrderServiceSOAP" name="OrderServiceSOAP">
			<soap:address location="http://tempuri.org/acmeOrders/WADDR/ProcessOrders"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
